### ISSUE TITLE
P2PU/mentor fork or this project for reporting issues?

### ISSUE THREAD

**Issue by scspaeth** [alexkehayias/mentor#18]
Your blog:
http://alexkehayias.tumblr.com/post/29349166671/introducing-open-source-project-based-mentorship

and the mentordev site at dotcloud make it clear that you invite participation and feedback:
http://mentordev-qu6we2kn.dotcloud.com/requests/

But it is not clear whether you want feedback here or in the p2pu/mentor fork of this project. I chose this one because of more recent activity but will change to whatever you prefer.

**Comment by alexkehayias** [comment]
For now send all feedback to this one. Thanks!

**Comment by scspaeth** [comment]
Thank you for initiating this project.
