### ISSUE TITLE
Projected Created Twice

### ISSUE THREAD

**Issue by 1l2p** [alexkehayias/mentor#2]
The project is created even before the final "Finish" button is clicked. I played around with the interface, but intentionally did not click Finish. I then went through the whole process again and clicked "Finish". 

The project ("kickstater campaign wingmanship" now shows up twice:

http://mentorship.p2pu.org/projects/

**Comment by alexkehayias** [comment]
I've deleted the duplicate project for now, will need to clear the form field upon save so that you don't accidentally do that again.
